# -*- coding: utf-8 -*-
"""text_combinator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kH3mMxTT6-t5GYHiiYPLbgKsGScc-_Ts
"""

!pip install tqdm
import sys, os
import datetime
import numpy as pd
import pandas as pd
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

# Load text from first half of each game
df = pd.read_csv('drive/Team Drives/Deep Learning Project/ken_cnn/text_dataset_60min.csv', sep='\t')
df.head(3)

df.shape

# Combine text comments into one long text for each game
texts = {}
duplicate_ids = []
for idx, row in tqdm(df.iterrows(), total=df.shape[0]):
  game_id = row['id_odsp']
  text = str(row['text'])
  
  if not game_id in texts:
    texts[game_id] = []
  else:
    duplicate_ids.append(idx)
  
  # Add to text list
  texts[game_id].append(text)
  
# Remove duplicate game ID
df.drop(df.index[duplicate_ids], inplace=True)

# Update to full long text
for game_id in tqdm(texts):
  long_text = " ".join(texts[game_id])
  df.loc[ int(df[ df['id_odsp'] == game_id ].index[0]), 'text' ] = long_text

df.shape

# Write to file
df.to_csv('drive/Team Drives/Deep Learning Project/ken_cnn/combined_text_dataset_60mins.csv', sep='\t')